// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlotbxrbnhzoxbylajwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsb3RieHJibmh6b3hieWxhandlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMzk0MDYsImV4cCI6MjA1ODkxNTQwNn0.pTJV3br6jyZWmhK2E9cY5jnwlFP6mlJuxo7QfRATRik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);